version: '3.8'

networks:
  mynetwork:
    external: true

services:
  bootstrap:
    build:
      context: .
      dockerfile: bootstrap.Dockerfile
    ports:
      - "8000:3000"
    networks:
      - mynetwork

  node1:
    container_name: node1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080" 
    networks:
      - mynetwork

  node2:
    container_name: node2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    networks:
      - mynetwork

  node3:
    container_name: node3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8080" 
    networks:
      - mynetwork

  node4:
    container_name: node4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8080" 
    networks:
      - mynetwork
  
